create table author
(
    id       int8 generated by default as identity,
    fio      varchar(255),
    primary key (id)
);

create table book
(
    id            int8 generated by default as identity,
    descr         varchar(2048),
    file_name     varchar(255),
    name          varchar(255) not null,
    page_count    int4 not null,
    book_pdf_name varchar(255),
    publish_year  int4 not null,
    author_id     int8 not null,
    genre_id      int8 not null,
    primary key (id)
);


create table genre
(
    id   int8 generated by default as identity,
    type varchar(255),
    primary key (id)
);

create table usr
(
    id       int8 not null,
    active   boolean,
    password varchar(255) not null,
    usr_name varchar(255) not null,
    primary key (id)
);

create sequence hibernate_sequence start 1 increment 1;

create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);

alter table if exists book add constraint book_author_id_fk foreign key (author_id) references author;
alter table if exists book add constraint book_genre_id_fk foreign key (genre_id) references genre;
alter table if exists user_role add constraint user_role_fk foreign key (user_id) references usr;